name: Validate manifests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: kubectl kustomize overlays/crc >/dev/null
      - run: pipx run yamllint==1.37.1 -d relaxed .
